### ISSUE TITLE
Trouble reproducing results

### ISSUE THREAD

**Issue by crazy-eddie** [tfc/nix_cmake_example#1]
The first two commands work great and I get a new build for each.  When I start using the release.nix commands though I run into trouble (tab completion is not working):

```
$ nix-build release.nix -A mdb-server-gcc-boost166
error: attribute 'mdb-server-gcc-boost166' in selection path 'mdb-server-gcc-boost166' not found
```
The only one that exists in the same listing that works is `mdb-webservice`.

The ones I'm most interested in trying and looking at are the integration tests.  None of the options you list that I have tried have worked.

Is this a WIP such that these should not work, am I missing an important piece of nix, or should this work and it isn't for me?  I *just* installed nix and this is pretty much the first thing I've tried to do with it.  Very interested in your work.  Thank you.

**Comment by crazy-eddie** [comment]
I needed https://github.com/hedning/nix-bash-completions to enable tab completion before getting the lists associated with the prefixes in the readme.  Some of the sample runs need to be updated in the README, but getting tab completion helps resolve the necessary attributes.

**Comment by tfc** [comment]
Hi @crazy-eddie,

this is not a WIP and this should all be working for everyone.
I also have a hydra job set up that build/tests it all: https://hydra.kosmosgame.com/jobset/github/nix_cmake_example#tabs-jobs

If something is not working, then i think it might be the following:

- Parts of the README claim things that are not right (any longer)
- Users of `nix` on different Linux distros may experience slight differences i am not aware of since i only use NixOS.

I am going to review the README and fix everything that is wrong/outdated.

But can you confirm that all nix expressions build without errors for you? If that would not be the case i would be really surprised.

**Comment by tfc** [comment]
I updated the README. Please let me know if anything is still missing.

**Comment by crazy-eddie** [comment]
It works great now.  The addition of the link to the tab-completion environment script will definitely help those of us using Nix the package manager and not the OS.

Thanks again for doing this.  I'm going to study it now to see how it works.

**Comment by crazy-eddie** [comment]
Would also like to say this is the best example of an integrated and complete, automated project I've found out and about.  It's not just a resource for NiX but a great example of doing it right.  So double thanks.

**Comment by tfc** [comment]
I am delighted to hear/read that it helps people unearthing nix's huge potential for their use cases. I  close this issue for now, feel free to reopen or to open a new one once there is another problem.
